meta_name: "TheSocialBookclub"
meta_title: "TheSocialBookclub - Read a book. Together."
meta_description: "Join a passionate community, read together, and explore the joy of books at The Social Book Club."
meta_image: "meta_cover.jpg" # should exist in `app/assets/images/`
